<?php

namespace astrid\AdBundle\Repository;

/**
 * cityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cityRepository extends \Doctrine\ORM\EntityRepository
{
}
