astrid_ad_homepage:
    path:     /
    defaults: { _controller: astridAdBundle:Ad:home }

astrid_ad_new:
    path:     /new
    defaults: { _controller: astridAdBundle:Ad:newAd }

astrid_ad_view:
    path:     /view/{id}
    defaults: { _controller: astridAdBundle:Ad:view }

astrid_ad_edit:
    path:     /edit/{id}
    defaults: { _controller: astridAdBundle:Ad:editAd }

astrid_ad_delete:
    path:     /delete/{id}
    defaults: { _controller: astridAdBundle:Ad:deleteAd }

astrid_ad_deletephoto:
    path:     /deletephoto/{id}
    defaults: { _controller: astridAdBundle:Ad:deletePhoto}




astrid_api_get:
    path:     /api/get
    defaults: {_controller: astridAdBundle:Api:get}
    methods: [GET]

astrid_api_add:
    path:     /api/add
    defaults: {_controller: astridAdBundle:Api:add}
    methods: [POST]

astrid_api_ad:
    path:     /api/ad
    defaults: {_controller: astridAdBundle:Api:ad}
    methods: [GET]

astrid_api_edit:
    path:     /api/edit
    defaults: {_controller: astridAdBundle:Api:edit}
    methods: [POST]

astrid_api_addcity:
    path:     /api/addcity
    defaults: {_controller: astridAdBundle:Api:addCity}
    methods: [POST]

astrid_api_addcat:
    path:     /api/addcat
    defaults: {_controller: astridAdBundle:Api:addCat}
    methods: [POST]

astrid_api_addphoto:
    path:     /api/addphoto
    defaults: {_controller: astridAdBundle:Api:addPhoto}
    methods: [POST]

astrid_api_delete:
    path:     /api/delete
    defaults: {_controller: astridAdBundle:Api:delete}
    methods: [DELETE]

astrid_api_deletephoto:
    path:     /api/deletephoto
    defaults: {_controller: astridAdBundle:Api:deletePhoto}
    methods: [DELETE]




